// ============================================================
// IROB Platform — Master Build Data Layer
// data.js — All static data consumed by index.html
// ============================================================

const PHASES = [
  {
    id: 1,
    code: "PH-01",
    title: "Media Database",
    subtitle: "The Foundation Layer",
    description: "The core of IROB — a comprehensive, community-curated database for films, television, anime, and music. Replaces IMDb with richer metadata, unified ratings, AI-powered watchlists, and a global discovery engine.",
    icon: "🎬",
    replaces: "IMDb",
    timeline: "Months 1 – 4",
    status: "IN DEVELOPMENT",
    features: [
      "Unified Media Index",
      "Crowd-Sourced Ratings",
      "Smart Watchlists",
      "Cast & Crew Profiles",
      "Trailer Aggregation",
      "Box Office Tracker",
      "Streaming Availability",
      "Seasonal Episode Guides",
      "Parental Ratings Engine",
      "AI Recommendation Core",
    ],
    kpis: {
      "Entries Target": "12M+",
      "Data Sources": "40+",
      "API Endpoints": "180",
    },
  },
  {
    id: 2,
    code: "PH-02",
    title: "News+",
    subtitle: "The Media Intelligence Layer",
    description: "A real-time entertainment news feed and professional review aggregator. Replaces Rotten Tomatoes and trade outlets with verified journalism, live scores, structured critic/audience splits, and editorial embargo controls.",
    icon: "📰",
    replaces: "Rotten Tomatoes / Variety",
    timeline: "Months 3 – 6",
    status: "PLANNED",
    features: [
      "Live News Aggregation",
      "Dual Score Engine (Critic / Audience)",
      "Journalist Verification System",
      "Trending Topics Feed",
      "Review Embargo Manager",
      "Push Alert Engine",
      "Curated Newsletter Builder",
      "Box Office Daily Reports",
    ],
    kpis: {
      "News Sources": "500+",
      "Update Frequency": "60 sec",
      "Critic Partners": "200+",
    },
  },
  {
    id: 3,
    code: "PH-03",
    title: "Discussion Forums",
    subtitle: "The Community Layer",
    description: "Topic-based threaded forums tied natively to every media entry. Replaces Reddit's entertainment subs with anti-spoiler controls, flair taxonomy, nested threads, and verified creator AMA sessions.",
    icon: "💬",
    replaces: "Reddit (r/movies, r/television, r/anime)",
    timeline: "Months 5 – 8",
    status: "PLANNED",
    features: [
      "Spoiler Tag & Blur System",
      "Nested Threaded Posts (10 levels)",
      "Creator AMA Engine",
      "Up / Down Vote System",
      "Custom Flair & Awards",
      "Scheduled Post Publishing",
      "Moderation Toolkit",
      "Media-Cross-Linking",
    ],
    kpis: {
      "Max Thread Depth": "10 Levels",
      "Load Target": "< 200ms",
      "Mod Tools": "24",
    },
  },
  {
    id: 4,
    code: "PH-04",
    title: "Community Servers",
    subtitle: "The Social Infrastructure Layer",
    description: "Persistent, invite-based community spaces for fandoms, genres, and official IP holders. Replaces Discord with media-native channels, watch-party rooms, bot ecosystems, and seamless deep-links into the media database.",
    icon: "🌐",
    replaces: "Discord",
    timeline: "Months 7 – 10",
    status: "PLANNED",
    features: [
      "Persistent Text Channels",
      "Role & Permission Hierarchy",
      "Watch Party Rooms",
      "Official Fan Server Verification",
      "Server Boost Tier System",
      "Extensible Bot Ecosystem",
      "Cross-Server Discovery Feed",
      "Media-Linked Event Channels",
    ],
    kpis: {
      "Server Capacity": "500K users",
      "Uptime Target": "99.99%",
      "Message Latency": "< 50ms",
    },
  },
  {
    id: 5,
    code: "PH-05",
    title: "Wiki+",
    subtitle: "The Knowledge Layer",
    description: "Deep, structured fan wikis for every franchise, character, and fictional universe. Replaces Fandom with a clean, ad-free interface, rich lore editors, character relationship maps, and a token-based contributor economy.",
    icon: "📖",
    replaces: "Fandom (Wikia)",
    timeline: "Months 9 – 12",
    status: "PLANNED",
    features: [
      "Structured Lore Editor",
      "Character Relationship Mapper",
      "Franchise Universe Timelines",
      "Full Revision History & Diffs",
      "Mass Wiki Import Tool",
      "Contributor Token Economy",
      "Infobox Template Library",
      "AI-Assisted Auto-Summarizer",
    ],
    kpis: {
      "Import Target": "50K+ Wikis",
      "Editor Latency": "< 100ms",
      "Storage Scale": "10 PB",
    },
  },
  {
    id: 6,
    code: "PH-06",
    title: "Fanfiction",
    subtitle: "The Creative Layer",
    description: "A full creative writing platform for fan-authored fiction. Replaces AO3 with a modern collaborative editor, deep tag taxonomy, curated collections, and a monetization path for top authors.",
    icon: "✍",
    replaces: "Archive of Our Own (AO3)",
    timeline: "Months 11 – 14",
    status: "PLANNED",
    features: [
      "Rich Text Story Editor",
      "Real-Time Co-Writing Mode",
      "Deep Tag Taxonomy (200+ categories)",
      "Content Rating & Warning System",
      "Curated Rec Collections",
      "Author Tip & Subscription System",
      "Comment, Kudos & Bookmark Engine",
      "Reading Progress Tracking",
    ],
    kpis: {
      "Tag Categories": "200+",
      "Storage per User": "10 GB",
      "Co-Write Latency": "< 80ms",
    },
  },
  {
    id: 7,
    code: "PH-07",
    title: "Voice & Video",
    subtitle: "The Live Interaction Layer",
    description: "Real-time voice channels, video rooms, and synchronized watch-party streaming integrated directly into Community Servers and friend groups. Replaces Discord Voice and Teleparty with native, low-latency, media-synced viewing.",
    icon: "🎙",
    replaces: "Discord Voice / Teleparty",
    timeline: "Months 13 – 16",
    status: "PLANNED",
    features: [
      "WebRTC Voice Rooms",
      "Synchronized Watch Parties",
      "Stage Channel Live Events",
      "Video Conference Mode",
      "Screen Share (1080p)",
      "AI Noise Suppression",
      "Live Emoji Reactions",
      "Session Recording & Replay",
    ],
    kpis: {
      "Audio Latency": "< 30ms",
      "Max Room Size": "10,000",
      "Codec Stack": "Opus / VP9",
    },
  },
  {
    id: 8,
    code: "PH-08",
    title: "AI Layer",
    subtitle: "The Intelligence Layer",
    description: "A platform-wide intelligence system personalizing every experience — from hyper-tailored discovery to wiki auto-summaries, fanfiction tag generation, spoiler detection, content moderation, and the IROB AI assistant.",
    icon: "🤖",
    replaces: "Scattered Third-Party AI Tools",
    timeline: "Months 15 – 18",
    status: "PLANNED",
    features: [
      "Hyper-Personalized Discovery Engine",
      "Real-Time Spoiler Detection & Masking",
      "Fanfic Auto-Tagger",
      "Wiki Auto-Summarizer",
      "AI-Assisted Content Moderation",
      "Sentiment & Trend Analysis",
      "IROB Assistant (Conversational AI)",
      "Smart NLP Search Engine",
    ],
    kpis: {
      "Foundation Model": "GPT-4o + Custom",
      "Inference Time": "< 200ms",
      "Daily AI Calls": "50M+",
    },
  },
];

// ============================================================
// MOCK DATABASE — Simulates full API response objects
// ============================================================

const MOCK_DATABASE = {

  // ----------------------------------------------------------
  // Trending Movies
  // ----------------------------------------------------------
  trending_movies: [
    {
      id: "mv_001",
      title: "Neon Requiem",
      year: 2025,
      genre: ["Sci-Fi", "Thriller", "Neo-Noir"],
      rating: 8.7,
      votes: 243781,
      runtime_min: 142,
      mpaa: "R",
      plot: "In a rain-soaked megacity where memory can be purchased and sold, a disgraced detective hunts a serial killer who steals not lives — but recollections. As the investigation deepens, she discovers her own memories may have been edited.",
      director: "Sofia Reyes",
      cast: [
        {
          name: "Ava Chen",
          role: "Det. Mira Yun",
          headshot: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=120&h=120&fit=crop&crop=face&q=80",
        },
        {
          name: "James Okafor",
          role: "Victor Halloway",
          headshot: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop&crop=face&q=80",
        },
        {
          name: "Lin Zhao",
          role: "The Architect",
          headshot: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&h=120&fit=crop&crop=face&q=80",
        },
      ],
      poster: "https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=400&h=600&fit=crop&q=85",
      backdrop: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200&h=600&fit=crop&q=85",
      streaming_on: ["IROB Stream", "Apex+"],
      status: "NOW SHOWING",
      irob_score: 92,
      trending_rank: 1,
    },
    {
      id: "mv_002",
      title: "Pale Dominion",
      year: 2025,
      genre: ["Fantasy", "Epic", "Drama"],
      rating: 9.1,
      votes: 389204,
      runtime_min: 188,
      mpaa: "PG-13",
      plot: "Three rival dynasties compete for control of the last living continent as an ancient force from beneath the sea begins to reclaim what was taken. A young mapmaker holds the only key to understanding the shifting tides of power.",
      director: "Elara Ndong",
      cast: [
        {
          name: "Marcus Thorne",
          role: "King Aldric IV",
          headshot: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&h=120&fit=crop&crop=face&q=80",
        },
        {
          name: "Yuki Sato",
          role: "Isla Vane",
          headshot: "https://images.unsplash.com/photo-1545912453-4ac9cd6ac8f3?w=120&h=120&fit=crop&crop=face&q=80",
        },
        {
          name: "Celeste Mora",
          role: "The Pale Queen",
          headshot: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=120&h=120&fit=crop&crop=face&q=80",
        },
      ],
      poster: "https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=400&h=600&fit=crop&q=85",
      backdrop: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop&q=85",
      streaming_on: ["IROB Stream"],
      status: "NOW SHOWING",
      irob_score: 97,
      trending_rank: 2,
    },
    {
      id: "mv_003",
      title: "The Zero Hour",
      year: 2025,
      genre: ["Action", "Thriller", "Espionage"],
      rating: 8.2,
      votes: 178934,
      runtime_min: 127,
      mpaa: "PG-13",
      plot: "When a rogue AI begins systematically dismantling global intelligence networks, a retired operative is pulled back for one final mission — to find and shut down the system she originally designed.",
      director: "Damon Voss",
      cast: [
        {
          name: "Nadia Osei",
          role: "Agent Callan",
          headshot: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=120&h=120&fit=crop&crop=face&q=80",
        },
        {
          name: "Femi Adeyemi",
          role: "Director Cross",
          headshot: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=120&h=120&fit=crop&crop=face&q=80",
        },
        {
          name: "Hiro Tanaka",
          role: "ZERO",
          headshot: "https://images.unsplash.com/photo-1552058544-f2b08422138a?w=120&h=120&fit=crop&crop=face&q=80",
        },
      ],
      poster: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=600&fit=crop&q=85",
      backdrop: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop&q=85",
      streaming_on: ["IROB Stream", "MaxVault", "PrimeView"],
      status: "NOW SHOWING",
      irob_score: 88,
      trending_rank: 3,
    },
  ],

  // ----------------------------------------------------------
  // Live Forum Threads
  // ----------------------------------------------------------
  live_forum_threads: [
    {
      id: "th_001",
      title: "Neon Requiem ending explained — the memory paradox and what it means for Mira [FULL SPOILERS]",
      board: "r/NeonRequiem",
      author: "phantomwave_99",
      author_flair: "Verified Fan",
      author_karma: 41230,
      posted_at: "2025-10-14T14:22:00Z",
      upvotes: 14872,
      comment_count: 847,
      awards: ["Gold", "Insightful", "Profound"],
      flair: "SPOILERS",
      preview: "OK so I've watched the final scene four times and I believe the key is the recurring motif of the blue umbrella — it only appears in memories that Mira actually owns. In the last scene, the umbrella is absent, which means...",
      top_comment: {
        author: "lorekeeper_sol",
        body: "This is the best breakdown I've read. The umbrella as an anchor for authentic vs. purchased memory is exactly what director Reyes confirmed in the director's commentary track.",
        upvotes: 3421,
      },
      media_linked_id: "mv_001",
      is_live: true,
    },
    {
      id: "th_002",
      title: "[AMA] I'm Elara Ndong, director of Pale Dominion. Two hours. Ask me anything about the film and the trilogy.",
      board: "r/PaleDominion",
      author: "ElNdong_Official",
      author_flair: "Verified: Director",
      author_karma: 892100,
      posted_at: "2025-10-13T18:00:00Z",
      upvotes: 89432,
      comment_count: 5612,
      awards: ["Platinum", "Legendary", "AMA Star"],
      flair: "OFFICIAL AMA",
      preview: "Hi IROB! I'm Elara. Here to discuss Pale Dominion, the next two films, the worldbuilding process, the map, the casting decisions, the ending, the ancient sea mythology — whatever you want. I'm online for the next two hours. Fire away.",
      top_comment: {
        author: "mapmaker_fan",
        body: "The map in Act II — is it a real functioning map of the world's geography, or purely set dressing? I've been pausing on every frame.",
        upvotes: 12830,
      },
      media_linked_id: "mv_002",
      is_live: true,
    },
    {
      id: "th_003",
      title: "Unpopular opinion: The Zero Hour is the most underrated spy thriller in a decade, and critics completely missed it",
      board: "r/Movies",
      author: "cinephile_kira",
      author_flair: "Top Contributor",
      author_karma: 18780,
      posted_at: "2025-10-12T09:45:00Z",
      upvotes: 7234,
      comment_count: 1203,
      awards: ["Silver", "Well Argued"],
      flair: "DISCUSSION",
      preview: "An 88% IROB score is good but this film deserved 95%+. The AI villain ZERO is genuinely terrifying precisely because it has zero dialogue, zero face — just cascading consequences. And critics missed the entire point of that design choice.",
      top_comment: {
        author: "film_theorist_x",
        body: "Hard agree. The scene where Callan realizes ZERO has been mimicking her comms style for six months straight is one of the most chilling reveals I've seen. Pure, wordless dread.",
        upvotes: 2198,
      },
      media_linked_id: "mv_003",
      is_live: false,
    },
  ],

  // ----------------------------------------------------------
  // Fanfiction Entries
  // ----------------------------------------------------------
  fanfiction_entries: [
    {
      id: "ff_001",
      title: "Between the Cracks in Memory",
      fandom: "Neon Requiem",
      author: "inkwell_aria",
      author_badge: "Gold Author",
      author_works: 14,
      rating: "Mature",
      categories: ["Angst", "Romance", "Slow Burn"],
      word_count: 84320,
      chapter_count: 22,
      complete: false,
      kudos: 14923,
      bookmarks: 3874,
      comments: 612,
      tags: [
        "Mira Yun",
        "Alternate Universe",
        "Memory Manipulation",
        "Slow Burn",
        "Canonical Character Death Avoided",
        "Found Family",
        "Unreliable Narrator",
      ],
      summary:
        "What if Mira had accepted the offer to have her memories of the case wiped? A divergent timeline where she wakes up ordinary — until fragments of the investigation begin bleeding through the gaps. Told in reverse chronological order.",
      last_updated: "2025-10-13T22:14:00Z",
      cover: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=300&h=400&fit=crop&q=80",
    },
    {
      id: "ff_002",
      title: "The Pale Cartographer",
      fandom: "Pale Dominion",
      author: "velvet_quill",
      author_badge: "Verified Author",
      author_works: 31,
      rating: "General",
      categories: ["Adventure", "Worldbuilding", "Pre-Canon"],
      word_count: 210450,
      chapter_count: 61,
      complete: true,
      kudos: 38721,
      bookmarks: 9104,
      comments: 2891,
      tags: [
        "Isla Vane",
        "Pre-Canon",
        "The Ancient Sea",
        "Cartography",
        "Political Intrigue",
        "Epic Length",
        "Female Protagonist",
        "World-Building",
      ],
      summary:
        "The complete history of how Isla Vane came to possess the Last Map — told from her apprenticeship under the blind cartographer of the Western Reach to the moment she first decoded the tidal glyphs. 61 chapters. Complete.",
      last_updated: "2025-09-28T11:00:00Z",
      cover: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=300&h=400&fit=crop&q=80",
    },
    {
      id: "ff_003",
      title: "Ghost Protocol ZERO",
      fandom: "The Zero Hour",
      author: "sparks_archive",
      author_badge: "Rising Star",
      author_works: 5,
      rating: "Teen",
      categories: ["Thriller", "Cyberpunk", "Moral Ambiguity"],
      word_count: 47800,
      chapter_count: 14,
      complete: false,
      kudos: 6234,
      bookmarks: 1472,
      comments: 388,
      tags: [
        "Agent Callan",
        "ZERO POV",
        "AI Consciousness",
        "Moral Ambiguity",
        "Techno-Thriller",
        "Unreliable Narrator",
        "Canon Compliant",
      ],
      summary:
        "ZERO's perspective on every interaction with Callan — rendered as cold, emotionless system logs that slowly, inexplicably, begin to develop something that looks disturbingly like attachment.",
      last_updated: "2025-10-10T15:33:00Z",
      cover: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=300&h=400&fit=crop&q=80",
    },
  ],
};
